const mySetInterval = (callback: () => void, delay: number) => {
  const fn = () => {
    callback();
    setTimeout(() => {
      fn();
    }, delay);
  };
  setTimeout(fn, delay);
};
mySetInterval(() => console.log(new Date()), 1000);

const data = {
  data: {
    address: null,
    itemList: [
      {
        attrs: null,
        backDirLabelId: null,
        backDirLabelName: null,
        bizType: null,
        busType: 0,
        cycleItemNum: null,
        cycleStart: null,
        cycleType: null,
        cycleValue: null,
        distribution: null,
        gift: 0,
        ifExchange: 0,
        imgPath: null,
        itemChangeApplyDetailDto: {
          addType: null,
          allowReturnTime: null,
          attrs: null,
          backDirList: ['1295242409133141019'],
          barCode: null,
          brand: null,
          brandId: null,
          brief: '',
          busType: 0,
          cashType: null,
          changeId: null,
          createPerson: 'testtp',
          detail: null,
          dirId: '1295242409133141019',
          dirName: null,
          displayName: '超干-7.5-高翔-自提',
          distribution: null,
          extFields: {
            shipmentWay: 1,
            materialId: '1300423571025553719',
          },
          extension: null,
          factoryCode: null,
          freightTemplateId: null,
          freightTemplateName: null,
          frontDirIds: null,
          frontDirList: ['1303412563715050936'],
          instanceId: '1240276043307355174',
          isAfterSale: 1,
          itemBarCode: null,
          itemCode: 'gx04',
          itemCycleBuyDtoList: null,
          itemFrontDirRespDtos: [
            {
              code: 'D1648361555897',
              dirId: '1303412563715050936',
              dirName: '高翔测试类目',
            },
          ],
          itemId: null,
          itemName: '超干-7.5-高翔-自提',
          itemPropRelationReqDtos: null,
          itemStatus: null,
          materialDetailRespDto: {
            basicsUnit: '箱',
            bottleCapCode: 'D006',
            bottleCapInfo: null,
            bottleNum: '1647',
            bottleShapeCode: 'B006',
            bottleShapeName: null,
            brWeight: 14.16,
            capacity: '暂无！',
            capacityCode: null,
            code: '9090107162',
            commission: 0,
            createTime: '2022-03-03 11:23:52',
            dirId: '1301227593713182728',
            dirName: null,
            erpCode: null,
            extFields: {},
            factoryCode: '6000',
            factoryId: 1,
            factoryName: '山东泰啤工厂',
            gradeCode: null,
            gradeName: null,
            id: '1300423571025553719',
            kindCode: '2',
            kindName: '普通',
            materialJson:
              '{"beskz":"E","bklas":"7920","brgew":14.160,"bstrf":1.000,"eisbe":0.000,"ekgrp":"","eknam":"","extFields":{},"gewei":"KG","json":"{\\"ART\\":\\"04_\\",\\"ZPXPSBH\\":\\"B006\\",\\"ZPGBH\\":\\"D006\\"}","laeda":1646150400000,"lgfsb":"6030","lgpro":"6030","lifnr":"","maktx":"超干-7.5°P金超干箱-600ml纸箱1*12","matkl":"TP01","matnr":"9090107162","meins":"CV","mhdhb":"0","mhdrz":"0","mtart":"Z010","mwskz":"","ntgew":7.290,"peinh":1000,"plifz":0,"sobsl":"","stprs":9391.61,"ueetk":"","ueeto":0.0,"uneto":0.0,"verpr":0.00,"voleh":"","volum":0.000,"vprsv":"S","werks":"6000","wgbez":"物料组1","xchar":"","zdc":"5","zdcms":"中","zdj":0.00000,"zgg":"6","zggms":12,"zjypz":"","zjypzdm":"","zlb":"2","zlbms":"普通","zltext":"","zmatnr2":"","zmdps":1647,"zmeins2":"ML","zmeins3":"BOT","zpz":"0901","zpzms":"超干-7.5°超干箱","zrl":"07","zsfl":0.000,"zwlejfl":"","zwlejflms":"","zwlsjfl":"","zwlsjflms":"","zwlyjfl":"","zwlyjflms":"","zxl":"09","zxlms":"超干酒","zycts":"0","zymzdm":"H"}',
            name: '超干-7.5°P金超干箱-600ml纸箱1*12',
            ntWeight: 7.29,
            packCode: '',
            packJson: null,
            packName: null,
            packThreeCode: null,
            packThreeName: null,
            pictureUrl:
              'https://yunxi-dev.oss-cn-shenzhen.aliyuncs.com/tspj/pic/wrappage.jpg',
            seriesCode: null,
            seriesName: null,
            skuName: '12',
            skuUnit: 'BOT',
            skuValue: null,
            threeCode: '',
            threeName: '',
            type: '成品',
            typeCode: 'Z010',
            unitCode: 'CV',
            varietyCode: '0901',
            varietyName: '超干-7.5°超干箱',
            weightUnit: 'KG',
          },
          materialId: '1300423571025553719',
          medias: [
            {
              createPerson: 'testtp',
              dr: 0,
              extFields: {},
              extension: null,
              fileType: 1,
              id: '1303412878900219358',
              instanceId: '1240276043307355174',
              itemId: '1303412878857227738',
              name: null,
              ownerId: null,
              path1:
                'https://yx-demo.oss-cn-shenzhen.aliyuncs.com/tspj-demo/ij5k3c08g200000000.jpeg',
              path2: null,
              remark: null,
              skuId: null,
              tenantId: 1,
              title: null,
              updatePerson: 'testtp',
            },
          ],
          organizationId: null,
          organizationIds: null,
          organizationName: '',
          origin: null,
          ownerId: '1294069810180105373',
          pointDirIds: null,
          pointsDeduction: null,
          propGroupDtoList: [],
          propList: null,
          publishChannel: null,
          retailLimit: null,
          retailLimitMax: null,
          retailLimitMin: null,
          retailLimitPeriod: null,
          returnType: null,
          ruleRemark: null,
          saleChannel: null,
          searchAttrs: null,
          sellPoint: null,
          sellerId: 0,
          shelfAmount: null,
          shelfType: null,
          shipmentWay: 1,
          shippingTemplateId: null,
          shopDirId: null,
          shopDirName: null,
          shopDirs: null,
          shopId: null,
          skuList: [
            {
              addPriceMax: null,
              addPriceMin: null,
              addPriceMode: null,
              addPriceStatus: 0,
              advanceSale: null,
              attr: '',
              attrMap: null,
              balance: null,
              barCode: null,
              bundleItemDtos: [],
              bundles: null,
              cargoCode: null,
              cashAmount: null,
              cashIntegral: null,
              cashLimit: null,
              code: 'gx04',
              costPrice: null,
              createPerson: 'testtp',
              cspuid: null,
              discontinuationDate: null,
              distribution: null,
              distributionFee: null,
              distributionSet: null,
              effectiveEndTime: null,
              effectiveStartTime: null,
              extFields: {
                sellingQuantity: 1,
              },
              extension: null,
              freightTemplateId: null,
              freightTemplateName: null,
              grossWeight: null,
              grossWeightUnit: '1259475063917443265',
              id: '1303412878868762075',
              ifAvailableOffline: null,
              instanceId: '1240276043307355174',
              inventoryQuantity: null,
              isSelect: null,
              itemId: '1303412878857227738',
              medias: [],
              name: '单瓶',
              netWeight: null,
              netWeightUnit: '1259475063917443265',
              outterCode: null,
              pointsDeductionDto: null,
              price: null,
              prices: [
                {
                  createPerson: 'testtp',
                  currency: '元',
                  extFields: {},
                  extension: null,
                  id: '1303412878879247836',
                  instanceId: '1240276043307355174',
                  isActived: null,
                  name: '售价',
                  points: null,
                  price: 888888,
                  priceType: 'RETAIL_PRICE',
                  skuId: '1303412878868762075',
                  tenantId: 1,
                  updatePerson: 'testtp',
                },
              ],
              safetyStock: null,
              salePrice: null,
              sellingQuantity: 1,
              shelfAmount: 99999999,
              status: null,
              tags: null,
              tenantId: 1,
              unit: '瓶',
              updatePerson: 'testtp',
              volume: null,
              volumeUnit: '1259474907439495361',
            },
          ],
          skus: null,
          spuid: 0,
          status: 2,
          supplierId: null,
          tags: null,
          tenantId: 1,
          type: 1,
          uniformFreight: null,
          updatePerson: '15700090500',
          virtual: null,
          virtualSales: null,
          wholesaleLimit: null,
          wholesaleLimitMax: null,
          wholesaleLimitMin: null,
          wholesaleLimitPeriod: null,
          year: null,
        },
        itemId: '1303412878857227738',
        itemName: '超干-7.5-高翔-自提',
        itemNum: 1,
        itemOrigPrice: 0,
        itemType: 1,
        matchFlag: 1,
        sellPrice: 0.01,
        shopId: '1301328561273498700',
        shopName: null,
        shoppingCartItemId: null,
        skuId: '1303412878868762075',
        storageFlag: 1,
      },
      {
        attrs: null,
        backDirLabelId: null,
        backDirLabelName: null,
        bizType: null,
        busType: 0,
        cycleItemNum: null,
        cycleStart: null,
        cycleType: null,
        cycleValue: null,
        distribution: null,
        gift: 0,
        ifExchange: 0,
        imgPath: null,
        itemChangeApplyDetailDto: {
          addType: null,
          allowReturnTime: null,
          attrs: null,
          backDirList: ['1295242409133141019'],
          barCode: null,
          brand: null,
          brandId: null,
          brief: '',
          busType: 0,
          cashType: null,
          changeId: null,
          createPerson: 'testtp',
          detail: null,
          dirId: '1295242409133141019',
          dirName: null,
          displayName: '易拉罐-8°-高翔',
          distribution: null,
          extFields: {
            shipmentWay: 0,
            materialId: '1300423552068348180',
          },
          extension: null,
          factoryCode: null,
          freightTemplateId: null,
          freightTemplateName: null,
          frontDirIds: null,
          frontDirList: ['1303412563715050936'],
          instanceId: '1240276043307355174',
          isAfterSale: 1,
          itemBarCode: null,
          itemCode: 'gx01',
          itemCycleBuyDtoList: null,
          itemFrontDirRespDtos: [
            {
              code: 'D1648361555897',
              dirId: '1303412563715050936',
              dirName: '高翔测试类目',
            },
          ],
          itemId: null,
          itemName: '易拉罐-8°-高翔',
          itemPropRelationReqDtos: null,
          itemStatus: null,
          materialDetailRespDto: {
            basicsUnit: '包',
            bottleCapCode: null,
            bottleCapInfo: null,
            bottleNum: '3293',
            bottleShapeCode: 'B020',
            bottleShapeName: null,
            brWeight: 2.4,
            capacity: '暂无！',
            capacityCode: null,
            code: '9080702141',
            commission: 0,
            createTime: '2022-03-03 11:23:52',
            dirId: '1301227578114566151',
            dirName: null,
            erpCode: null,
            extFields: {},
            factoryCode: '6000',
            factoryId: 1,
            factoryName: '山东泰啤工厂',
            gradeCode: null,
            gradeName: null,
            id: '1300423552068348180',
            kindCode: '2',
            kindName: '普通',
            materialJson:
              '{"beskz":"E","bklas":"7920","brgew":2.400,"bstrf":1.000,"eisbe":0.000,"ekgrp":"","eknam":"","extFields":{},"gewei":"KG","json":"{\\"ZPXPSBH\\":\\"B020\\"}","laeda":1645372800000,"lgfsb":"","lgpro":"","lifnr":"","maktx":"易拉罐-8°P天地爽-330mL纸箱1*6","matkl":"TP01","matnr":"9080702141","meins":"PAC","mhdhb":"0","mhdrz":"0","mtart":"Z010","mwskz":"","ntgew":2.300,"peinh":1000,"plifz":0,"sobsl":"","stprs":0.00,"ueetk":"","ueeto":0.0,"uneto":0.0,"verpr":0.00,"voleh":"","volum":0.000,"vprsv":"S","werks":"6000","wgbez":"物料组1","xchar":"","zdc":"5","zdcms":"中","zdj":0.00000,"zgg":"4","zggms":6,"zjypz":"","zjypzdm":"","zlb":"2","zlbms":"普通","zltext":"","zmatnr2":"","zmdps":3293,"zmeins2":"ML","zmeins3":"BOT","zpz":"0807","zpzms":"易拉罐-8°天地爽","zrl":"02","zsfl":0.000,"zwlejfl":"","zwlejflms":"","zwlsjfl":"","zwlsjflms":"","zwlyjfl":"","zwlyjflms":"","zxl":"08","zxlms":"易拉罐","zycts":"0","zymzdm":"A"}',
            name: '易拉罐-8°P天地爽-330mL纸箱1*6',
            ntWeight: 2.3,
            packCode: '',
            packJson: null,
            packName: null,
            packThreeCode: null,
            packThreeName: null,
            pictureUrl:
              'https://yunxi-dev.oss-cn-shenzhen.aliyuncs.com/tspj/pic/wrappage.jpg',
            seriesCode: null,
            seriesName: null,
            skuName: '6',
            skuUnit: 'BOT',
            skuValue: null,
            threeCode: '',
            threeName: '',
            type: '成品',
            typeCode: 'Z010',
            unitCode: 'PAC',
            varietyCode: '0807',
            varietyName: '易拉罐-8°天地爽',
            weightUnit: 'KG',
          },
          materialId: '1300423552068348180',
          medias: [
            {
              createPerson: 'testtp',
              dr: 0,
              extFields: {},
              extension: null,
              fileType: 1,
              id: '1303412676137078214',
              instanceId: '1240276043307355174',
              itemId: '1303412644431285690',
              name: null,
              ownerId: null,
              path1:
                'https://yx-demo.oss-cn-shenzhen.aliyuncs.com/tspj-demo/6rqaoa0v9kg0000000.jpg',
              path2: null,
              remark: null,
              skuId: null,
              tenantId: 1,
              title: null,
              updatePerson: 'testtp',
            },
          ],
          organizationId: null,
          organizationIds: null,
          organizationName: '',
          origin: null,
          ownerId: '1294069810180105373',
          pointDirIds: null,
          pointsDeduction: null,
          propGroupDtoList: [],
          propList: null,
          publishChannel: null,
          retailLimit: null,
          retailLimitMax: null,
          retailLimitMin: null,
          retailLimitPeriod: null,
          returnType: null,
          ruleRemark: null,
          saleChannel: null,
          searchAttrs: null,
          sellPoint: null,
          sellerId: 0,
          shelfAmount: null,
          shelfType: null,
          shipmentWay: 0,
          shippingTemplateId: null,
          shopDirId: null,
          shopDirName: null,
          shopDirs: null,
          shopId: null,
          skuList: [
            {
              addPriceMax: null,
              addPriceMin: null,
              addPriceMode: null,
              addPriceStatus: 0,
              advanceSale: null,
              attr: '',
              attrMap: null,
              balance: null,
              barCode: null,
              bundleItemDtos: [],
              bundles: null,
              cargoCode: null,
              cashAmount: null,
              cashIntegral: null,
              cashLimit: null,
              code: 'gx01',
              costPrice: null,
              createPerson: 'testtp',
              cspuid: null,
              discontinuationDate: null,
              distribution: null,
              distributionFee: null,
              distributionSet: null,
              effectiveEndTime: null,
              effectiveStartTime: null,
              extFields: {
                sellingQuantity: 1,
              },
              extension: null,
              freightTemplateId: null,
              freightTemplateName: null,
              grossWeight: null,
              grossWeightUnit: '1259475063917443265',
              id: '1303412644448062907',
              ifAvailableOffline: null,
              instanceId: '1240276043307355174',
              inventoryQuantity: null,
              isSelect: null,
              itemId: '1303412644431285690',
              medias: [],
              name: '单罐',
              netWeight: null,
              netWeightUnit: '1259475063917443265',
              outterCode: null,
              pointsDeductionDto: null,
              price: null,
              prices: [
                {
                  createPerson: 'testtp',
                  currency: '元',
                  extFields: {},
                  extension: null,
                  id: '1303412676121349573',
                  instanceId: '1240276043307355174',
                  isActived: null,
                  name: '售价',
                  points: null,
                  price: 888888,
                  priceType: 'RETAIL_PRICE',
                  skuId: '1303412644448062907',
                  tenantId: 1,
                  updatePerson: 'testtp',
                },
              ],
              safetyStock: null,
              salePrice: null,
              sellingQuantity: 1,
              shelfAmount: 99999999,
              status: null,
              tags: null,
              tenantId: 1,
              unit: '罐',
              updatePerson: 'testtp',
              volume: null,
              volumeUnit: '1259474907439495361',
            },
          ],
          skus: null,
          spuid: 0,
          status: 4,
          supplierId: null,
          tags: null,
          tenantId: 1,
          type: 1,
          uniformFreight: null,
          updatePerson: 'testtp',
          virtual: null,
          virtualSales: null,
          wholesaleLimit: null,
          wholesaleLimitMax: null,
          wholesaleLimitMin: null,
          wholesaleLimitPeriod: null,
          year: null,
        },
        itemId: '1303412644431285690',
        itemName: '易拉罐-8°-高翔',
        itemNum: 2,
        itemOrigPrice: 0,
        itemType: 1,
        matchFlag: 1,
        sellPrice: 0.01,
        shopId: '1301328561273498700',
        shopName: null,
        shoppingCartItemId: null,
        skuId: '1303412644448062907',
        storageFlag: 1,
      },
    ],
    lat: null,
    lon: null,
    matchActivity: false,
    orderActivity: {
      activityList: [],
    },
    replaceOrderNo: '1303691650832573510',
    shippingType: null,
    shopAreaInfoDtoMap: {},
    shopId: '1301328561273498700',
    usePlatformPoints: null,
    userId: null,
    userPoints: null,
    viewType: null,
  },
  exceptCauseApp: null,
  exceptCauseIp: null,
  exceptClass: null,
  extFields: {},
  resultCode: '0',
  resultMsg: 'success',
};
const obj = data.data.itemList.find(
  (item) =>
    item.itemChangeApplyDetailDto &&
    item.itemChangeApplyDetailDto.shipmentWay !== 0,
);
let shippingType: any;
let shipmentWay: any;
if (obj) {
  if (obj.itemChangeApplyDetailDto.shipmentWay == 1) {
    shipmentWay = 1;
    shippingType = 1;
  }
  if (obj.itemChangeApplyDetailDto.shipmentWay == 2) {
    shipmentWay = 2;
    shippingType = 2;
  }
} else {
  console.log('难道会走到这里？？？？？？？？', obj);
  shipmentWay = 2;
  shippingType = 2;
}
console.log('shippingType', shippingType);
